/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/drone.glb --output src/DroneModel.jsx --shadows --transform --types 
Files: public/drone.glb [19.77MB] > C:\Users\rafis\Documents\CUF\Assignment 4\frontend\src\drone-transformed.glb [757.31KB] (96%)
Author: Count Infinity (https://sketchfab.com/countinfinity)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/futuristic-delivery-drone-48d0997629ee4cc9836775a523651017
Title: Futuristic Delivery Drone
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function DroneModel(props) {
  const { nodes, materials } = useGLTF('/drone-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Object_2.geometry} material={materials.Cargo} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_3.geometry} material={materials.Drone} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials.Flaps} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/drone-transformed.glb')
